### ISSUE TITLE
Chord Shapes are incorrect

### ISSUE THREAD

**Issue by L0FKA** [andulv/RSTabExplorer#1]
Chord Shapes are applied incorrect and mess up all track with chords.

**Comment by andulv** [comment]
I play the bass, so I am not very familiar with chords and I don't fully understand what is wrong.

Could you provide me with a screenshot or something of a song with chord shapes that are applied incorrect, together with a description of what the correct result should be?

**Comment by L0FKA** [comment]
This one was fixed in 0.3.x version..

**Comment by andulv** [comment]
@L0FKA You mentioned you had a library for Gp5 export. Is the source available somewhere? Do you think this is something you could implement in this project?

**Comment by L0FKA** [comment]
No, I won't implement anything in this project, for now.
Here is that Library http://phoneguitartab.codeplex.com/
You need a Tablature module It contains GP5 writer (best format for now, its fully(almost) supported by EOF). I planned to use it with RSToolkit as SNG>TAB but it would be not so fast.
