### ISSUE TITLE
Crash on load [via Reddit]

### ISSUE THREAD

**Issue by Jamedjo** [andulv/RSTabExplorer#5]
Roscopecotrain

> This is brilliant, kudos for the hard work! I've given it a preliminary run through, I have found that loading disc tracks or DLC causes the program to crash. Is this a known bug, or is there something that may be causing this? Either way I cant wait to learn this as well as through RS

Wiggles69

> There's no progress bar, or anything to indicate it's working.
> If you open up one of the DLC's that is just one massive file, then it'll take ages to load (i wander off and do something for 5 mins to give it a good chance)

http://www.reddit.com/r/rocksmith/comments/24cd0u/rocksmith_tab_explorer_github/ch5u9ax

**Comment by kimpixel** [comment]
can confirm that

**Comment by Jamedjo** [comment]
Should be using a background thread until it starts rendering the track on the latest version.

Which version are you on?
Do the buttons at the top grey out?
Does it freeze up for or does it crash with an error?
How long does it freeze for?
Is it fine if you open a single dlc psarc file?

Thanks

**Comment by kimpixel** [comment]
Which version are you on?
-v0.0.3

Do the buttons at the top grey out?
-no

Does it freeze up for or does it crash with an error?
-no error

How long does it freeze for?
- no freeze, direct crash

Is it fine if you open a single dlc psarc file?
- yes

Windows 8.1

**Comment by Jamedjo** [comment]
Ah, not the same issue as Wiggles69 then.

Could be that it can't find your Rocksmith folder and crashes when it tries to open an empty file.

If open the load psarc dialog and then cancel it do you get the same crash?
Is it in your Steam folder, a Steam library folder or a folder specifically for Rocksmith?

Could you try a version which includes d0b3aecd such as http://s000.tinyupload.com/?file_id=52245939847444570634

**Comment by kimpixel** [comment]
the game is on my desktop. (specific folder)
With you new .exe i was able to cancel the "load psarc dialog".
But crashes also

**Comment by Jamedjo** [comment]
Could you open your steam config file (somewhere like C:\Program Files (x86)\Steam\config\config.vdf) in a text editor and check if it mentions your install folder anywhere.

**Comment by kimpixel** [comment]
i have no "steam" - its a portable version

**Comment by Jamedjo** [comment]
I can't think of a way to detect your install folder. Unless there was a registry key in use which could be detected by [Procmon](http://technet.microsoft.com/en-us/sysinternals/bb896645.aspx).

This version should handle the error better: http://s000.tinyupload.com/?file_id=02548210977143237659

**Comment by kimpixel** [comment]
can i add the registry key manual?

**Comment by Jamedjo** [comment]
I think you misunderstood.
The code currently works by checking a steam registry key for the steam folder, followed by the steam config file for the install folder. Failing that you have to find the psarc files manually.

On my computer there are various registry keys set by steam which I could re-write it to use. If you could setup Procmon as with `Path *contains* Rocksmith` added as a filter and then run Rocksmith, and see if you have `HKLM\SOFTWARE\Wow6432Node\Ubisoft\Rocksmith2014\installdir` set so I could potentially re-write it to use that when/if I get time.

But for now, non steam installations are not supported, since you can just manually select the psarcs.

![screenshot-p141](https://cloud.githubusercontent.com/assets/1028741/2871275/ace92014-d2ff-11e3-9d71-fa6cc9a919d7.png)

**Comment by kimpixel** [comment]
my idea is to make a Preferences Dialog with optional autofill with all the required Paths and other things

**Comment by Jamedjo** [comment]
You're welcome to fork the project and add that feature!

Or you can open a new issue with that as a feature request. But it sounds like a lot of work, needs all those settings to be set somewhere, makes the UI more complicated, and could probably be better solved by autodetecting the folder.

I'm going to close this issue as both crashes look to be fixed.

**Comment by kimpixel** [comment]
Ok - sorry my c++ know how is rusty. It takes to much time for me.
I can buy me the original Game for PC (I bought both RS version on PS3)

Or donate a solution for me. ??
