### ISSUE TITLE
Some notes don't match [via Reddit]

### ISSUE THREAD

**Issue by Jamedjo** [andulv/RSTabExplorer#8]
avastreg

> I noticed that some notes are on the wrong line/string (at least I noticed this into the song "Mary Jane Last Dance", just look at the intro)

jamedjo

> Haven't touched that part of the code yet, but I'll take a look
> A really specific example will help me troubleshoot it:
> - What bar was the error in. (Numbered in red)
> - What should the notes have been?
> - Which track? (Rhythm/Combo/Bass)
> - Did you change the Difficulty or tick "Only include..." ?

avastreg

> Hi, i'd like to help as much as possible, here's a screen of the piece
> http://i.imgur.com/lXrfXCp.png
> Lead, Combo, no tick on "Only include..."
> The error is present in bar 5 and 6 (the first two bar where there are errors) and it's not only the wrong line/string, it doesn't really match.
> The right version has to be like this
> http://filebin.ca/1KqfscpCHxnd/MaryJaneBar5-6.pdf
> http://filebin.ca/1KqfyFGBjGX3/MaryJaneBar5-6.gpx
> Transcribed right from the track (with a bit of approximation)
> Bar 1-4 are OK, i don't have verified other bars.
> Thank you for verifying it! If it helps, i can upload the video i've recorded to transcribe the track.

**Comment by apelliciari** [comment]
Hi, i'm avastreg on reddit. If you need additional information on this, I'll be glad to help.

**Comment by Jamedjo** [comment]
It looks like this is caused by looking for ChordId 9, and instead picking chord template with array index 9.

```
"ChordId": 9,
"ChordName": "Am7",
```

...

```
"ChordId": 28,
"ChordName": "D",
```

The data structure from RocksmithToolkitLib doesn't include the chordId, probably because most songs number the chords 0..1..2... but in this one it is authored as 3,7,9,12,13,15,16,26,27,28 etc.

**Comment by Jamedjo** [comment]
I found a video on YouTube which helped, https://www.youtube.com/watch?v=YlcuDDCgv3M

**Comment by Jamedjo** [comment]
Looks like your pdf now (ignoring the dotted notes). I don't want to relaes it untested as it likely changes at least one chord in around a third of the tracks.

Would be appreciated if you could test it a bit. I've uploaded a compiled version to http://s000.tinyupload.com/?file_id=52245939847444570634

**Comment by apelliciari** [comment]
Thanks! i'll try to play it and i'll let you know asap

2014-05-03 17:56 GMT+02:00 James EdJo notifications@github.com:

**Comment by apelliciari** [comment]
I think Mary Jane is pretty accurate now! so imho you can close this

**Comment by Jamedjo** [comment]
Sweet!
